### ISSUE TITLE
[recsys] Dimension of B_output

### ISSUE THREAD

**Issue by bjbschmitt** [prog-eval/prog-eval#2]
Given
`h3 = h2 @ W_output + B_output`

in recsys and considering the dimensions
`h2 -> [batch_size x hidden_dim]`
`W_output -> [hidden_dim x num_items]`
`h2 @ W_output ->  [batch_size x num_items]`

shouldn't the dimension of B_output be num_items?

**Comment by prog-eval** [comment]
@bjbschmitt yes -- good catch.  updating docs now.
